# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.11 # https://pyreadiness.org/3.10
  - pip=23.2.2 # https://pip.pypa.io/en/stable/news
  - pip:
      - rpaframework==28.6.2
      - openpyxl==3.1.5
      - trio==0.26.2
      - httpx==0.27.2
      - robocorp-workitems
